import { vi } from 'vitest';

// Create mock for useStore
export const useStore = vi.fn(() => ({
  isAuthenticated: true,
  modalMode: null,
  isCreateModalOpen: false,
  isManageModalOpen: false,
  isViewTemplateModalOpen: false,
  initialRoleId: null,
  toggleCreateModal: vi.fn(),
  toggleManageModal: vi.fn(),
  toggleViewTemplateModal: vi.fn(),
  selectedTemplate: null,
  selectedTemplateForPrompt: null,
  setSelectedTemplate: vi.fn(),
  setSelectedTemplateForPrompt: vi.fn(),
  deleteTemplate: vi.fn(),
  addRole: vi.fn(),
  updateRole: vi.fn(),
  deleteRole: vi.fn(),
  selectedRole: '',
  setSelectedRole: vi.fn(),
  setInitialRoleId: vi.fn(),
  prompts: [],
  addPrompt: vi.fn(),
  selectedPrompt: null,
  setSelectedPrompt: vi.fn(),
  setModalMode: vi.fn(),
  searchTerm: '',
  setSearchTerm: vi.fn(),
  currentUser: null,
  isAdmin: false,
  login: vi.fn(),
  logout: vi.fn(),
  isLogoClicked: false,
  toggleLogoClick: vi.fn(),
  isEnhanceModalOpen: false,
  enhanceModalContent: '',
  openEnhanceModal: vi.fn(),
  closeEnhanceModal: vi.fn(),
  setEnhanceModalContent: vi.fn(),
}));
